
export const SPRINT_TRACKER_GRID_DATA = 'SPRINT_TRACKER_GRID_DATA';
export const SPRINT_TRACKER_TOTAL_DATA = 'SPRINT_TRACKER_TOTAL_DATA';
export const LOADER_STATE = 'LOADER_STATE';
export const SPRINT_TRACKER_STATE ='SPRINT_TRACKER_STATE';
export const SPRINT_PROGRESS_STATE = 'SPRINT_PROGRESS_STATE';
